Animals table
pinkmoon25/vet_clinic_database pull request #1
Opened 2022-09-12 21:53 UTC by PinkMoon25

### In this PR I have:

- Created a Vet_Clinic database
- Created a table for Animals data
- Created schema to add the data to animals table
- Write SQL to query the animals data

Below are the screenshots of query results: 
![Screenshot from 2022-09-12 22-38-20](https://user-images.githubusercontent.com/97521557/189764946-dee4e0fc-24eb-42dc-b7c6-5c37e5e1189b.png)
![Screenshot from 2022-09-12 22-37-02](https://user-images.githubusercontent.com/97521557/189765002-360f4b68-13ce-44a9-b313-b6a7e1e9af2a.png)

Thank you :+1:

2022-09-12 22:06 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @PinkMoon25, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Professional Readme
✔️ Correct Gitflow
✔️ Good job so far

## Required 
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-12 22:06 UTC, sja-thedude commented on queries.sql
> +SELECT * FROM animals WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-01-01';
- [x] Kindly make sure that your end date is '2019/31/12' as per the requirements you have to display list the name of all animals born between 2016 and 2019.
- [x] Also make sure to add screenshot for this in pull request as the previous was not right.

2022-09-13 06:17 UTC, PinkMoon25 commented on queries.sql
> +SELECT * FROM animals WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-01-01';
Thank you @sja-thedude , I have made the necessary changes and attached the screenshot of the query result in the PR description

2022-09-13 06:22 UTC, sja-thedude approved these changes
## Project Approved 👍 

Hi @PinkMoon25, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights:
- All requirements completed
- Professional readme

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-13 07:03 UTC, merged